# This github action will build a Python package module from source
---
name: Build Python Package
description: Builds the given package. For this, installs the required packages and pass a QA analysis for PEP8 syntaxis.

author: Marius Crisan
branding:
  icon: package
  color: blue

inputs:

  source-path:
    description: Path to the package source files
    required: true
    type: string

  package-path:
    description: Path to the package definition files
    required: true
    type: string

  is-test-package:
    description: True if is a test package for testPypi
    required: false
    type: boolean
    default: false

runs:
  using: composite
  steps:

  - name: Install module dependencies
    run: |
      if [ -f "${{ inputs.package-path }}/requirements.txt" ]; then pip install -r ${{ inputs.package-path }}/requirements.txt; fi
    shell: bash

  - name: Lint with pylint
    run: |
      pylint --rcfile=.vscode/.pylintrc ${{ inputs.source-path }}/*
    shell: bash

  - name: Run tests
    run: |
      if ${{ inputs.is-test-package }}; then
        test_path='${{ inputs.source-path }}/tests/test*.py'
        if ls $test_path > /dev/null 2>&1; then
          pytest $test_path
        fi
      fi
    shell: bash

  - name: Check new version
    id: get-version
    run: |
      if ${{ inputs.is-test-package }}; then
        is_test='test'
      fi
      python3 ${{ github.action_path }}/get_version.py ${{ inputs.package-path }} $is_test
    shell: bash

  - name: Build a binary wheel and a source tarball
    run: |
      python3 -m build --sdist --wheel --outdir dist/ ${{ inputs.package-path }}
    shell: bash
    env:
      SETUPTOOLS_SCM_PRETEND_VERSION: ${{ steps.get-version.outputs.new-version }}
