# This github action will build a Python package module from source
---
name: Build Python Package
description: Builds the given package. For this, installs the required packages and pass a QA analysis for PEP8 syntaxis.

author: Marius Crisan
branding:
  icon: package
  color: blue

inputs:

  source-path:
    description: Path to the pacakge source files
    required: true
    type: string

  pacakge-path:
    description: Path to the package definition files
    required: true
    type: string

runs:
  using: composite
  steps:

  - name: Install module dependencies
    run: |
      if [ -f "${{ pacakge-path }}/requirements.txt" ]; then pip install -r ${{ pacakge-path }}/requirements.txt; fi
    shell: bash

  - name: Lint with pylint
    run: |
      pylint --rcfile=.vscode/.pylintrc ${{ inputs.source-path }}/*
    shell: bash

  - name: Run tests
    run: |
      test_path='${{ inputs.source-path }}/tests/test*.py'
      if ls $test_path > /dev/null 2>&1; then
        pytest $test_path
      fi
    shell: bash

  - name: Check new version
    id: get-version
    run: |
      python3 ${{ github.action_path }}/get_version.py ${{ inputs.source-path }}
    shell: bash

  - name: Build a binary wheel and a source tarball
    run: |
      python3 -m build --sdist --wheel --outdir dist/ ${{ inputs.source-path }}
    shell: bash
    env:
      SETUPTOOLS_SCM_PRETEND_VERSION: ${{ steps.get-version.outputs.new-version }}
